services:
  - type: web
    name: telegram-forwarder-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      cd backend
      npm ci --production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"